# Generated by Django 4.2.6 on 2023-10-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='profile',
            name='authority',
            field=models.CharField(default='Admin', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Full Time', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='break_time',
            field=models.IntegerField(default=3600),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary',
            field=models.IntegerField(default=10000),
        ),
    ]
