# Generated by Django 4.2.6 on 2023-10-13 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0003_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='time',
        ),
        migrations.AddField(
            model_name='logs',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 14, 28, 39, 283736)),
        ),
    ]
