# Generated by Django 4.2.6 on 2023-10-13 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0004_remove_logs_time_logs_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='logs',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
