# Generated by Django 4.2.6 on 2023-10-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0007_remove_profile_login_date_remove_profile_logout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='login_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='logout_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
