# Generated by Django 4.2.6 on 2023-10-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0008_alter_profile_login_time_alter_profile_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='legit_working_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
