# Generated by Django 4.2.6 on 2023-10-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0010_profile_profile_month_profile_profile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_year',
            field=models.CharField(default=2023, max_length=4),
        ),
    ]
