# Generated by Django 4.2.6 on 2023-10-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0014_alter_profile_profile_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_month',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_year',
        ),
    ]
