# Generated by Django 4.2.6 on 2023-10-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0016_profile_profile_month_profile_profile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='legit_working_time',
            field=models.CharField(default='0:0:0', max_length=200),
        ),
    ]
