# Generated by Django 4.2.6 on 2023-10-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0017_alter_profile_legit_working_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_on_break',
            field=models.BooleanField(default=False),
        ),
    ]
