# Generated by Django 4.2.6 on 2023-10-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0018_profile_is_on_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='break_end_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='break_start_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
