# Generated by Django 4.2.6 on 2023-10-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0019_profile_break_end_time_profile_break_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_break_time',
            field=models.CharField(default='0:0:0', max_length=200),
        ),
    ]
