# Generated by Django 4.2.6 on 2023-12-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR_App", "0020_profile_total_break_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_logged_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_month",
            field=models.CharField(default=12, max_length=2),
        ),
    ]
