# Generated by Django 4.2.6 on 2023-12-20 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR_App', '0022_profile_profile_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_minute',
            field=models.CharField(default=18, max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
