# Generated by Django 5.0 on 2023-12-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0023_remove_attendance_minute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='day',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='month',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='year',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
