# Generated by Django 5.0 on 2023-12-30 14:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0024_remove_attendance_day_remove_attendance_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='break_end_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='break_start_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='legit_working_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='logout_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_month',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_break_time',
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date(2023, 12, 30), null=True)),
                ('work_time', models.IntegerField(blank=True, default=0, null=True)),
                ('break_time', models.IntegerField(blank=True, default=0, null=True)),
                ('start_time', models.TimeField(blank=True, default=datetime.time(19, 5, 30, 69150), null=True)),
                ('end_time', models.TimeField(blank=True, default=datetime.time(19, 5, 30, 69150), null=True)),
                ('break_start_time', models.TimeField(blank=True, null=True)),
                ('break_end_time', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
