# Generated by Django 4.2.8 on 2023-12-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0025_alter_profile_profile_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_minute',
            field=models.CharField(default=4, max_length=2),
        ),
    ]
