# Generated by Django 5.0 on 2023-12-30 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0025_remove_profile_break_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='login_time',
            field=models.TimeField(blank=True, default=datetime.time(22, 11, 24, 724482), null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(22, 11, 24, 724482), null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(22, 11, 24, 724482), null=True),
        ),
    ]
