# Generated by Django 5.0 on 2023-12-31 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0026_performance_login_time_alter_performance_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='break_end_time',
            field=models.TimeField(blank=True, default=datetime.time(7, 57, 20, 539948), null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='break_start_time',
            field=models.TimeField(blank=True, default=datetime.time(7, 57, 20, 539948), null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 31), null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(7, 57, 20, 539948), null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='login_time',
            field=models.TimeField(blank=True, default=datetime.time(7, 57, 20, 539948), null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(7, 57, 20, 539948), null=True),
        ),
    ]
