# Generated by Django 5.0 on 2024-01-04 16:09

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0029_alter_performance_break_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='performance',
            name='break_end_time',
            field=models.TimeField(blank=True, default=datetime.time(21, 9, 6, 597370), null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='break_start_time',
            field=models.TimeField(blank=True, default=datetime.time(21, 9, 6, 597370), null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performance',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(21, 9, 6, 597370), null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='login_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
